ProfessionalWiki/PageApprovals

extension.json
psalm-baseline.xml
src/EntryPoints/REST/ApprovePageApi.php
src/EntryPoints/REST/UnapprovePageApi.php
src/PageApprovals.php
tests/PageApprovalsIntegrationTest.php
tests/integration/EntryPoints/REST/ApprovePageApiTest.php
tests/integration/EntryPoints/REST/UnapprovePageApiTest.php
tests/unit/PageApprovalsTest.php

For #3 
This adds the initial API stubs.
Use cases and presenters to come in a follow-up.

Add initial approve and unapprove APIs

---

composer.json
extension.json
phpstan-baseline.neon
psalm-baseline.xml
sql/PageApprovals.sql
src/Adapters/DatabaseApprovalLog.php
src/Adapters/DatabaseApproverRepository.php
src/Adapters/DatabaseHtmlRepository.php
src/EntryPoints/PageApprovalsHooks.php
tests/Adapters/DatabaseApprovalLogTest.php
tests/Adapters/DatabaseApproverRepositoryTest.php
tests/Adapters/DatabaseHtmlRepositoryTest.php
tests/Application/UseCases/EvaluateApprovalStateTest.php

Fixes https://github.com/ProfessionalWiki/PageApprovals/issues/5
At first I added try-catch blocks to DatabaseHtmlRepository for error handling and logging. After some consideration, I removed them, as I could not justify the added complexity. Quite annoying to test. And it's somewhat unrelastic for one of those DB calls to fail. If the DB is broken, the code won't get to this point. And even if it does happen, the user experience or the dev experience won't be improved by the try-catch.

Create DB tables and persistence services

---

extension.json

.CSS and .JS files were not loading. This PR fixes that. The reason we couldn't catch that earlier was probably that it was cached in the browser.
Before:
After:

Resources Load Fix

---

phpstan-baseline.neon
psalm-baseline.xml
src/Adapters/DatabasePendingApprovalRetriever.php
src/Adapters/InMemoryApproverRepository.php
src/Application/PendingApproval.php
src/Application/PendingApprovalRetriever.php
src/Application/UseCases/EvaluateApprovalState.php
src/EntryPoints/PageApprovalsHooks.php
tests/Adapters/DatabasePendingApprovalRetrieverTest.php

For https://github.com/ProfessionalWiki/PageApprovals/issues/24
`DatabasePendingApprovalRetriever` and `DatabasePendingApprovalRetrieverTest` are, in large part, AI-generated, and I have not fully reviewed them from first principles yet.
Query turned out to be more complex than I had imagined, but I don't see a way to simplify

Add PendingApprovalRetriever

---

extension.json
phpstan-baseline.neon
psalm-baseline.xml
resources/ApprovePage.js
src/EntryPoints/PageApprovalsHooks.php
templates/PageApprovalStatus.mustache

Context:
https://chat.professional.wiki/pro-wiki/pl/kas94puudtg7icjt9ndsnaf6ra
JS and CSS loads as usual.

Added seperate HTML template for Approval Status

---

extension.json
resources/ApprovePage.js
src/EntryPoints/REST/ApprovePageApi.php
src/EntryPoints/REST/UnapprovePageApi.php
src/PageApprovals.php
tests/Adapters/PageHtmlRetrieverTest.php
tests/EntryPoints/REST/ApprovePageApiTest.php
tests/EntryPoints/REST/UnapprovePageApiTest.php
tests/PageApprovalsIntegrationTest.php

For #37 
This replaces the page ID parameter with the revision ID. The page is retrieved from the revision.
Manually tested that the correct 409 response is returned when an outdated page is kept open for Approval or Unapproval.

Check revision ID in API

---

src/Application/UseCases/EvaluateApprovalState.php
tests/Application/UseCases/EvaluateApprovalStateTest.php

Fixes https://github.com/ProfessionalWiki/PageApprovals/issues/56
Also verified manually by loading the page and checking whats in the DB afterwards.

Avoid persisting multiple unapproval logs

---

src/EntryPoints/REST/ApprovePageApi.php
src/EntryPoints/REST/UnapprovePageApi.php
src/PageApprovals.php
tests/EntryPoints/REST/ApprovePageApiTest.php
tests/EntryPoints/REST/UnapprovePageApiTest.php

For https://github.com/ProfessionalWiki/PageApprovals/issues/54
Also needed to show the new approval details on a page without refresh.

Return approval state in API response

---

psalm-baseline.xml
src/Adapters/DatabaseApproverRepository.php
tests/Adapters/DatabaseApproverRepositoryTest.php

We should normalize the saving or retrieval of categories from the `approver_config` table (DatabaseApproverRepository), or alternatively wherever the retrieved approver categories are used (AuthorityBasedApprovalAuthorizer in #33).
See also https://github.com/ProfessionalWiki/PageApprovals/pull/33#discussion_r1660167517

Add category normalization

---

phpstan-baseline.neon
psalm-baseline.xml
src/Application/Approver.php
src/Application/UseCases/GetApproversWithCategories.php
src/EntryPoints/Specials/SpecialManageApprovers.php

To pass around an object, instead of a complex array.
This came up because I saw the complex array typehint along with the missing typehints.

Add Approver class

---

i18n/en.json
resources/ApprovePage.js
src/EntryPoints/REST/ApprovePageApi.php
src/EntryPoints/REST/UnapprovePageApi.php
tests/EntryPoints/REST/ApprovePageApiTest.php
tests/EntryPoints/REST/UnapprovePageApiTest.php

For #54
Mostly just generic placeholder messages. Feel free to make them more user-friendly.
Approve responses when the page is edited on another tab:
https://github.com/ProfessionalWiki/PageApprovals/assets/1428594/2fb83655-0034-4024-94ff-e13ed150f224
Unapprove responses when the page is edited on another tab:
https://github.com/ProfessionalWiki/PageApprovals/assets/1428594/4bd614b4-61f0-4e13-9b5f-b5caff53e919
Approve/Unapprove responses when the paeg is deleted on another tab:
https://github.com/ProfessionalWiki/PageApprovals/assets/1428594/116a566f-bf95-4d9b-a3e8-749e912e4e62

Add API response messages

---

i18n/en.json
i18n/qqq.json
src/EntryPoints/Specials/SpecialPendingApprovals.php
src/PageApprovals.php

For #23 
Instead of an empty table with only headers which looks broken.
No categories:
No pending approvals:

Show message when user has no categories or no pending approvals

---

resources/ApprovePage.js
resources/ManageApprovers.css
resources/PageApprovals.css
templates/ManageApprovers.mustache
templates/PageApprovalStatus.mustache

For: https://github.com/ProfessionalWiki/PageApprovals/issues/78

Renaming bootstrap classes

---

phpstan-baseline.neon
psalm-baseline.xml
src/Adapters/DatabaseApproverRepository.php
src/Adapters/InMemoryApproverRepository.php
src/Application/ApproverRepository.php
src/Application/UseCases/ApprovalUiQuery/ApprovalUiQuery.php
src/PageApprovals.php
tests/Adapters/DatabaseApproverRepositoryTest.php
tests/Application/UseCases/ApprovalUiQueryTest.php
tests/EntryPoints/PageApprovalsHooksTest.php

For: https://github.com/ProfessionalWiki/PageApprovals/issues/34
https://github.com/ProfessionalWiki/PageApprovals/assets/15813104/5b9f66d3-17db-4649-a276-bdcc7bdb6308

Show UI conditionally

---

resources/PageApprovals.css
src/Presentation/OutputPageUiPresenter.php
tests/EntryPoints/PageApprovalsHooksTest.php

For #89 
I forgot that the indicators system is the right way of adding "page status" things around the page header.
This way it is up to the skin to position it correctly.
Vector:
https://github.com/user-attachments/assets/1640fe61-cb94-4f4a-ab4a-712c6f2c1ba9
Vector 2022:
https://github.com/user-attachments/assets/b72621bf-0893-46c1-a718-de6ae1b487e4
Chameleon:
https://github.com/user-attachments/assets/f2672521-e19b-4567-bfec-f684ceabffb4
The Chameleon layout is slightly wrong, but that has more to do with how Chameleon positions the indicators next to the title. We can just add a fix on the wiki instead of adding a Chameleon-specific fix here (which might not even work when there are Chameleon customizations).

Add approve button as an indicator

---

src/EntryPoints/Specials/SpecialManageApprovers.php
tests/EntryPoints/Specials/SpecialManageApproversTest.php

For: https://github.com/ProfessionalWiki/PageApprovals/issues/93
https://github.com/user-attachments/assets/4122520e-a4f6-4d4b-9e14-f8d555809b93

Multiple categories users fix

---

psalm-baseline.xml
src/Adapters/AuthorityBasedApprovalAuthorizer.php
src/Adapters/DatabaseApproverRepository.php
src/Adapters/DatabasePendingApprovalRetriever.php
src/Adapters/InMemoryApproverRepository.php
src/Application/PendingApproval.php
src/Application/UseCases/GetApproversWithCategories.php
src/EntryPoints/Specials/SpecialPendingApprovals.php
tests/Adapters/AuthorityBasedApprovalAuthorizerTest.php
tests/Adapters/DatabaseApproverRepositoryTest.php
tests/Adapters/DatabasePendingApprovalRetrieverTest.php
tests/Application/UseCases/ApprovalUiQueryTest.php
tests/EntryPoints/Specials/SpecialManageApproversTest.php

High level changes:
* Use normalized category names (DBkey) only in persistence classes.
* Other classes work with the human-readable name 
Specific issues addressed:
* Special:ManageApprovers: removing categories with spaces
* On page: show indicator when category contains spaces

Refactor approver category name normalization

---

phpstan-baseline.neon
psalm-baseline.xml
src/EntryPoints/Specials/SpecialManageApprovers.php
templates/ManageApprovers.mustache
tests/EntryPoints/Specials/SpecialManageApproversTest.php

For: https://github.com/ProfessionalWiki/PageApprovals/issues/101
Although I didn't make many changes, there is mainly just one function for filtering approvers, but other approaches came to my mind. 
1- It might be cleaner to have separate Endpoints for Add/Delete Categories. If we do that, we will either have to refresh the page or manipulate the HTML with JS, which is also not very clean. 
2- Another approach might be to Delete the category from DB, but when to delete it also requires building some logic. 
3- We can also keep the approver name only on the FE and never send it to the BE unless it has categories, but then we will also have to manipulate HTML using JS, which is also not the cleanest way.
Updated Test:
https://github.com/user-attachments/assets/50822668-b317-4ec6-ad1a-84207 …

Hide row for zero categories

---

templates/ManageApprovers.mustache

For: https://github.com/ProfessionalWiki/PageApprovals/issues/114
It's a little tricky now because of our existing code and also the response we get from our POST request. It sends us the entire page. However, this script should get the job done; we can also put this JS in a separate file, although I don't see the reason to it at the moment. Please do test the code on the UI.
https://github.com/user-attachments/assets/793e6713-0551-4b58-bd95-fc62bf70f1c3

Focusing on the input after adding category

---

resources/ApprovePage.js
resources/Icons/approved-arrow-down.svg
resources/Icons/arrow-down.svg
resources/PageApprovals.css
templates/PageApprovalStatus.mustache

For: https://github.com/ProfessionalWiki/PageApprovals/issues/109
You can watch the video if you wanna see style changes in depth.
https://github.com/user-attachments/assets/faf53bc6-2416-4790-b8cc-a3d9b9df95f7

Differentiates between approver badge style and non-approver

---

src/Application/UseCases/EvaluateApprovalState.php
tests/Application/UseCases/EvaluateApprovalStateTest.php

Semantic Results Format Datatables contain ids that change on page load. This causes approval state evaluation to fail because the saved id is different.
This PR just addresses the SRF id issue.
----
Thoughts:
* Should we perhaps ignore all ids (and maybe classes)? We haven't run into other issues yet, but the idea is there could be future issues here and it could be argued ids/classes aren't really content (but the opposite can also be true if your ids/classes are intended to convey meaning, e.g., color changes for success/error).
* I briefly looked at whether we should persist the normalized HTML, but decided against it:
* we're normalizing the current HTML on page load anyway, so it's a bit clearer what's happening in the code
* if we run into future normalization issues then the …

Ignore SMW ids when evaluating approval state
