.github/workflows/ci.yml
phpstan-baseline.neon
psalm-baseline.xml
src/Application/PageApprovalAuthorizer.php
src/EntryPoints/REST/ApprovePageApi.php
src/EntryPoints/REST/UnapprovePageApi.php
src/PageApprovals.php
src/Persistence/AuthorityBasedPageApprovalAuthorizer.php
tests/TestDoubles/FailingPageApprovalAuthorizer.php
tests/TestDoubles/SucceedingPageApprovalAuthorizer.php
tests/integration/EntryPoints/REST/ApprovePageApiTest.php
tests/integration/EntryPoints/REST/UnapprovePageApiTest.php

For https://github.com/ProfessionalWiki/PageApprovals/issues/3

Add initial PageApprovalAuthorizer

---

phpstan-baseline.neon
psalm-baseline.xml
psalm.xml
src/Adapters/AuthorityBasedApprovalAuthorizer.php
src/Adapters/InMemoryApprovalLog.php
src/Adapters/InMemoryHtmlRepository.php
src/Application/ApprovalLog.php
src/Application/ApprovalState.php
src/Application/ApproverRepository.php
src/Application/HtmlRepository.php
src/PageApprovals.php

It pains me to have the test doubles not tested yet. I will use them when finishing https://github.com/ProfessionalWiki/PageApprovals/pull/11

Add persistence interfaces

---

src/EntryPoints/REST/ApprovePageApi.php
src/EntryPoints/REST/UnapprovePageApi.php

Minor presentation tweaks in APIs

---

src/EntryPoints/PageApprovalsHooks.php

Fixes error reported by @waximabbax https://github.com/ProfessionalWiki/PageApprovals/pull/16#discussion_r1649696480

Avoid special page errors in onOutputPageParserOutput

---

phpstan-baseline.neon
psalm-baseline.xml
src/Adapters/PageContentRetriever.php
tests/Adapters/PageContentRetrieverTest.php
tests/EntryPoints/REST/ApprovePageApiTest.php
tests/EntryPoints/REST/UnapprovePageApiTest.php
tests/PageApprovalsIntegrationTest.php

Add PageContentRetriever

---

phpstan-baseline.neon
psalm-baseline.xml
src/EntryPoints/PageApprovalsHooks.php
tests/EntryPoints/PageApprovalsHooksTest.php

One of the AC on https://github.com/ProfessionalWiki/PageApprovals/issues/2

Only show approval UI on the latest revision

---

phpstan-baseline.neon
psalm-baseline.xml
src/EntryPoints/REST/ApprovePageApi.php
src/PageApprovals.php
tests/Adapters/PageContentRetrieverTest.php
tests/EntryPoints/REST/ApprovePageApiTest.php
tests/EntryPoints/REST/UnapprovePageApiTest.php
tests/PageApprovalsIntegrationTest.php

For https://github.com/ProfessionalWiki/PageApprovals/issues/28

Save HTML in ApprovePageApi

---

src/EntryPoints/REST/UnapprovePageApi.php
tests/EntryPoints/REST/UnapprovePageApiTest.php

Fix Unapprove API response

---

README.md
phpstan-baseline.neon
psalm-baseline.xml
src/Application/ApproverRepository.php
src/EntryPoints/PageApprovalsHooks.php
src/PageApprovals.php

Manually tested
Fixes https://github.com/ProfessionalWiki/PageApprovals/issues/22
I will refactor this code, move it out of the hooks file, and add tests. You can already merge the PR, as it makes the UI functional.

Use real data in onOutputPageBeforeHTML

---

psalm-baseline.xml
src/Application/UseCases/ApprovalUiQuery/ApprovalUiQuery.php
src/Application/UseCases/ApprovalUiQuery/UiArguments.php
src/EntryPoints/PageApprovalsHooks.php
src/PageApprovals.php
src/Presentation/OutputPageUiPresenter.php

No new logic, tests still missing, but these can now be added as next step
Manually verified

Refactor to ApprovalUiQuery UC with Presenter

---

src/Application/UseCases/ApprovalUiQuery/ApprovalUiQuery.php
src/Application/UseCases/ApprovalUiQuery/UiArguments.php
src/EntryPoints/PageApprovalsHooks.php
src/Presentation/OutputPageUiPresenter.php
tests/Application/UseCases/ApprovalUiQueryTest.php
tests/PageApprovalsTest.php

Another step closer
Still need moar tests

Add ApprovalUiQueryTest

---

src/Application/UseCases/ApprovalUiQuery/ApprovalUiQuery.php

Same fix as #48 reapplied after #26

Fix error on special pages

---

extension.json
phpstan-baseline.neon
psalm-baseline.xml
src/Application/UseCases/GetApproversWithCategories.php
src/EntryPoints/Specials/SpecialApproverCategories.php
tests/EntryPoints/Specials/SpecialApproverCategoriesTest.php

Follow up to https://github.com/ProfessionalWiki/PageApprovals/pull/17

Improvements to SpecialApproverCategories and related code

---

tests/EntryPoints/Specials/SpecialApproverCategoriesTest.php

It probably is still better to run Add and Delete separately but this test shouldn't pass if the code on the production is broken for Adding and Deleting the category.

test fixed testAddDeleteCategoryAction

---

i18n/en.json

Add missing approver right messages

---

src/EntryPoints/Specials/SpecialManageApprovers.php
templates/ManageApprovers.mustache

This shows the page title in the browser tab, and the correct page heading.

Output Special page headers

---

extension.json
i18n/Aliases/Aliases.php
i18n/en.json
src/EntryPoints/Specials/SpecialPendingApprovals.php
src/PageApprovals.php

For #23 
Current state:
Page titles are links.

Add Pending Approvals Special Page

---

src/Application/ApprovalState.php

Comment: https://github.com/ProfessionalWiki/PageApprovals/pull/67#discussion_r1664336268

Code Refactor

---

resources/ApprovePage.js

From https://github.com/ProfessionalWiki/PageApprovals/pull/67/files#r1664341052
As originally added in https://github.com/ProfessionalWiki/PageApprovals/pull/63

Show API errors

---

.eslintrc
.github/workflows/ci.yml
.gitignore
.stylelintrc.json
Gruntfile.js
Makefile
README.md
package.json
resources/ApprovePage.js
resources/ManageApprovers.css
resources/PageApprovals.css

Based on the latest in the example extension: https://github.com/wikimedia/mediawiki-extensions-examples
With some default rules switched from "error" to "warn".

Add MediaWiki linting

---

src/Application/UseCases/ApprovalUiQuery/ApprovalUiQuery.php

For tests failing in 
https://github.com/ProfessionalWiki/PageApprovals/pull/85

Fixes test for MW above 1.39

---

extension.json
psalm-baseline.xml
src/EntryPoints/Specials/SpecialManageApprovers.php
src/PageApprovals.php
tests/EntryPoints/Specials/SpecialApproverCategoriesTest.php

Just a refactor. Doesn't fix anything.

Inject SpecialManageApprovers dependencies

---

tests/EntryPoints/Specials/SpecialManageApproversTest.php

I verified that this test fails on master branch.

Add test case for adding another category when multiple users have categories

---

src/Adapters/DatabasePendingApprovalRetriever.php
src/EntryPoints/Specials/SpecialPendingApprovals.php
tests/Adapters/DatabasePendingApprovalRetrieverTest.php

Fixed https://github.com/ProfessionalWiki/PageApprovals/commit/2bcc39358cc5d837a689a0ff5af5be80689d3d38#r145381529
Fixes https://github.com/ProfessionalWiki/PageApprovals/issues/104
Fixes https://github.com/ProfessionalWiki/PageApprovals/issues/106

PendingApprovals improvements

---

i18n/en.json

This is an imperative verb, and as a verb,
"log in" must be written as two words.

Correct message spelling

---

src/EntryPoints/Specials/SpecialManageApprovers.php
src/EntryPoints/Specials/SpecialPendingApprovals.php

Add special pages to the correct groups

---

src/EntryPoints/Specials/SpecialManageApprovers.php
src/PageApprovals.php
tests/EntryPoints/Specials/SpecialManageApproversTest.php

I'm a bit confus as to why that TODO was left in there

Complete right check TODO

---

README.md

Fix Packagist badges

---

i18n/en.json

As per https://github.com/ProfessionalWiki/PageApprovals/pull/120#issuecomment-2298401096

Page name capitalization consistent with standards

---

i18n/en.json
resources/ApprovePage.js
src/EntryPoints/REST/ApprovePageApi.php
src/PageApprovals.php
src/Presentation/OutputPageUiPresenter.php
templates/PageApprovalStatus.mustache
tests/EntryPoints/REST/ApprovePageApiTest.php

For: https://github.com/ProfessionalWiki/PageApprovals/issues/98

use standard i18n
